### ISSUE TITLE
Standardized JSON Output type?

### ISSUE THREAD

**Issue by dessalines** [ZigmundVonZaun/torrent-tracker-scraper#8]
Could you provide a `.json`output type to standardize the output? Perhaps set by a command line flag?

I'd love to see the output look something like this:
```
{ 
  tracker: "udp://tracker.coppersurfer.tk:6969",
  infoHash: "95105D919C10E64AE4FA31067A8D37CCD33FE92D",
  seeds: 5045,
  leechers: 742,
  completed: 79802
}
```

Then I could easily parse the output with other programs.

**Comment by ZigmundVonZaun** [comment]
This feature will be added to the next commit
