### ISSUE TITLE
Infinite stalls occasionally

### ISSUE THREAD

**Issue by dessalines** [ZigmundVonZaun/torrent-tracker-scraper#9]
I occasionally get infinite stalls on scrapes:

`...Using tracker udp://tracker.coppersurfer.tk:6969`

These should either retry after a timeout, and fail after a certain number of fetches, or implement a total timeout to prevent this from locking the thread forever.

**Comment by ZigmundVonZaun** [comment]
Will free up some time and look into the issue

**Comment by dessalines** [comment]
Thanks! I'm using this tracker scraper for a project of mine, so I might be issuing a few PRs here for it within the next week or so.

**Comment by ZigmundVonZaun** [comment]
I hope my project will help yours in achieving your goals
